# Generated by Django 4.1 on 2022-09-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
